### ISSUE TITLE
For Databricks Runtime 5.5 notebooks are failing after enabling monitoring

### ISSUE THREAD

**Issue by itsvikas** [mspnp/spark-monitoring#157]
We enabled this Spark monitoring on a cluster having Databricks Runtime version 5.5. The init script is completing successfully and cluster is starting fine, but all python commands are failing in notebooks, with 'Cancelled' error, as in attached screenshot. SQL commands are working fine. 

Tried this on multiple clusters with 5.5 runtime and got same issue.

Please help with resolution for this issue. Thanks.
![IMG_20211117_160554](https://user-images.githubusercontent.com/17883119/142185306-3142ab91-49a7-4774-af67-ee044297d299.jpg)

**Comment by itsvikas** [comment]
Driver logs errors:

Standard Error:
`/databricks/spark/conf/spark-env.sh: line 18: appends: command not found
log4j:WARN No appenders could be found for logger (com.databricks.conf.trusted.ProjectConf$).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
/databricks/spark/conf/spark-env.sh: line 18: appends: command not found
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0`

Log4j output:
`21/11/18 01:58:28 WARN PythonDriverWrapper: Failed to start repl ReplId-60ddd-28045-6d6a8-d
java.io.IOException: Cannot run program "/local_disk0/pythonVirtualEnvDirs/virtualEnv-fc7b77e5-75e2-4c4c-9aa4-14b7491da001/bin/python" (in directory "."): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.apache.spark.util.Utils$.executeCommand(Utils.scala:1352)
	at org.apache.spark.util.Utils$.executeAndGetOutput(Utils.scala:1378)
	at org.apache.spark.util.Utils$.executePythonAndGetOutput(Utils.scala:1419)
	at org.apache.spark.util.DatabricksUtils$.org$apache$spark$util$DatabricksUtils$$getPythonLibDirPath(DatabricksUtils.scala:559)
	at org.apache.spark.util.DatabricksUtils$$anonfun$getOrCreatePythonVirtualEnvDir$1.apply$mcV$sp(DatabricksUtils.scala:622)
	at org.apache.spark.util.DatabricksUtils$.withStripedLock(DatabricksUtils.scala:356)
	at org.apache.spark.util.DatabricksUtils$.getOrCreatePythonVirtualEnvDir(DatabricksUtils.scala:606)
	at com.databricks.backend.daemon.driver.PythonDriverLocal$.com$databricks$backend$daemon$driver$PythonDriverLocal$$createPythonSubprocess(PythonDriverLocal.scala:1309)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.launchPython(PythonDriverLocal.scala:432)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.startPython0(PythonDriverLocal.scala:1089)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.startPython(PythonDriverLocal.scala:1140)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.init(PythonDriverLocal.scala:1173)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.<init>(PythonDriverLocal.scala:1181)
	at com.databricks.backend.daemon.driver.PythonDriverWrapper.instantiateDriver(DriverWrapper.scala:728)
	at com.databricks.backend.daemon.driver.DriverWrapper.setupRepl(DriverWrapper.scala:299)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:218)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 17 more
21/11/18 01:58:28 WARN PythonDriverWrapper: setupRepl:ReplId-60ddd-28045-6d6a8-d: at the end, the status is Error(ReplId-60ddd-28045-6d6a8-d,java.io.IOException: Cannot run program "/local_disk0/pythonVirtualEnvDirs/virtualEnv-fc7b77e5-75e2-4c4c-9aa4-14b7491da001/bin/python" (in directory "."): error=2, No such file or directory)
21/11/18 01:58:28 INFO DriverCorral$: Cleaning the wrapper ReplId-60ddd-28045-6d6a8-d (currently in status Stopped(ReplId-60ddd-28045-6d6a8-d))
21/11/18 01:58:28 INFO DriverCorral$: sending shutdown signal for REPL ReplId-60ddd-28045-6d6a8-d
21/11/18 01:58:28 WARN PythonDriverWrapper: Repl ReplId-60ddd-28045-6d6a8-d is already shutting down: Stopped(ReplId-60ddd-28045-6d6a8-d)
21/11/18 01:58:28 INFO DriverCorral$: sending the interrupt signal for REPL ReplId-60ddd-28045-6d6a8-d
21/11/18 01:58:28 INFO DriverCorral$: waiting for localThread to stop for REPL ReplId-60ddd-28045-6d6a8-d
21/11/18 01:58:28 INFO DriverCorral$: ReplId-60ddd-28045-6d6a8-d successfully discarded
`

**Comment by hallihan** [comment]
@itsvikas I just tested on an Azure Databricks 5.5 extended support and did not see the error.  Can you provide more detail on the cluster configuration (specific runtime version, Python version, etc.).  

Also, this line in your log output makes me wonder if something is amiss in the spark-monitoring.sh script: `/databricks/spark/conf/spark-env.sh: line 18: appends: command not found`.  If I look at the resulting spark-env.sh on a 5.5 cluster after the init script runs, the only instance of the word "appends" is on line 17 and it is in a comment. Is it possible that some edit or processing caused a word wrap?

Also, as a reminder, 5.5 is currently in extended support, and will be removed from the build of spark-monitoring after Dec 31, 2021. (https://docs.microsoft.com/azure/databricks/release-notes/runtime/releases)

**Comment by itsvikas** [comment]
@hallihan I am using 5.5 Databricks Extended Support runtime, below is my full cluster configuration. I am facing this issue only with Python, all others like SQL, Scala, R seem to work fine. Changing Python 2 to 3 also didn't make any difference. Also I tried on different workspaces, but see same issue.

And as far as editing the spark-monitoring.sh script is concerned, I am using the same automated program to update the script for all different clusters, and its working fine for all other runtimes.

`{
    "num_workers": 1,
    "cluster_name": "Test_5.5",
    "spark_version": "5.5.x-esr-scala2.11",
    "spark_conf": {},
    "azure_attributes": {
        "first_on_demand": 1,
        "availability": "ON_DEMAND_AZURE",
        "spot_bid_max_price": -1
    },
    "node_type_id": "Standard_DS3_v2",
    "driver_node_type_id": "Standard_DS3_v2",
    "ssh_public_keys": [],
    "custom_tags": {},
    "spark_env_vars": {},
    "autotermination_minutes": 20,
    "enable_elastic_disk": true,
    "cluster_source": "UI",
    "init_scripts": [
        {
            "dbfs": {
                "destination": "dbfs:/databricks/spark-monitoring/spark_scala_version/2.4.3_2.11/spark-monitoring.sh"
            }
        }
    ],
    "cluster_id": "....."
}`

**Comment by hallihan** [comment]
I have not been able to replicate this issue on a 5.5 cluster, and 5.5 is no longer supported.  Please open a new issue if you see the same behavior on a supported cluster version.
