### ISSUE TITLE
Failed to schedule batch because first message size 72281742 exceeds batch size limit 26214400 (bytes).

### ISSUE THREAD

**Issue by Naveen1453** [mspnp/spark-monitoring#190]
We are facing this issue while running a spark job.

Failed to schedule batch because first message size 72281742 exceeds batch size limit 26214400 (bytes).
log4j:ERROR Error sending logging event to Log Analytics
java.lang.RuntimeException: Failed to schedule batch because first message size 72281742 exceeds batch size limit 26214400 (bytes).
	at com.microsoft.pnp.client.GenericSendBuffer.send(GenericSendBuffer.java:94)
	at com.microsoft.pnp.client.loganalytics.LogAnalyticsSendBufferClient.sendMessage(LogAnalyticsSendBufferClient.java:43)
	at com.microsoft.pnp.logging.loganalytics.LogAnalyticsAppender.append(LogAnalyticsAppender.java:52)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:576)
	at org.apache.spark.internal.Logging.logError(Logging.scala:94)
	at org.apache.spark.internal.Logging.logError$(Logging.scala:93)
	at org.apache.spark.listeners.UnifiedSparkListener.logError(UnifiedSparkListener.scala:21)
	at org.apache.spark.listeners.UnifiedSparkListener.logSparkListenerEvent(UnifiedSparkListener.scala:75)
	at org.apache.spark.listeners.UnifiedSparkListener.onOtherEvent(UnifiedSparkListener.scala:44)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:86)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)

Is there a way this could be chunked and sent to Azure Monitor? Also are we just sending the application specific logs which is available in log4j output which we are logging or does it have all the logs that spark job is generating?

Because we are logging only few lines in our entire application and it would never go beyond 25 MB.

**Comment by hallihan** [comment]
See the documentation at: https://github.com/mspnp/spark-monitoring#logging-event-size-limit - you can rebuild the library with `EXCEPTION_ON_FAILED_SEND` set to false to have the library drop these oversized messages without generating an exception.

The library's default configuration sends everything.  You can look at https://github.com/mspnp/spark-monitoring/blob/main/docs/filtering.md if you want to limit the scope of logging.

**Comment by Naveen1453** [comment]
Hi @hallihan, Can this be enhanced to send chunks of data instead of sending the whole data and failing it if it's size exceeds the maximum size? This would be great

**Comment by hallihan** [comment]
Unfortunately the design of the library does not allow for deep processing like this. This library is a thin layer that is involved in every logging call, so analyzing large chunks of JSON data, and reshaping it, would incur significant memory and CPU cost for the workload.  Additionally there's no capability available at the Log Analytics side to "re-assemble" the chunks.

Single log messages that exceed the buffer limit are pretty rare, and often indicate that the workload is doing something like logging data chunks from the from the workload.  If you configure [cluster logging to dbfs](https://docs.microsoft.com/azure/databricks/clusters/configure#cluster-log-delivery) you can download the logs after a short run, and try to identify what is causing the large log messages.

**Comment by hallihan** [comment]
No further follow up noted.
