### ISSUE TITLE
DBR 12.2 LTS - Logs not captured in log analytics 

### ISSUE THREAD

**Issue by venkatsunil5** [mspnp/spark-monitoring#216]
Hello Team,
We are upgrading our databricks run time version to 12.2 LTS. We have created the following files:
1. log4j_layout_template_json_2_17_2.jar
2. spark-monitoring_1.0.0.jar
3. Spark-monitoring.sh
4. sparkLayout.json

When we are spinning up the General Purpose cluster, we noticed that logs are not sent to log analytics. Also, noticed some errors in the driver logs:

standard error:

java.io. IOException: Error sending to Log Analytics
at com.microsoft.pp.client.loganalytics.LogAnalyticsclient.send(LogAnalyticsclient.java:167)
at com.microsoft.pp.client.loganalytics.LogAnalyticsSendBufferTask.process(LogAnalyticsSendBuffer
New
at com.microsoft.pp.client. GenericsendBufferTask.run(GenericsendBufferTask. java: 148) at java.base/java.util.concurrent. ThreadPoolexecutor.runworker(ThreadPoolexecutor.java:1128)
at java.base/java.til.concurrent. ThreadPoolexecutor$worker. run(ThreadPoolexecutor.java:628) at java.base/java.lane.Thread.run(Thread.iava:829\
at java.base/java.lang. Thread. run (Thread. java: 829)
Caused by: javax.net.ss1.sSLException: Unexpected error: java.security. InvalidAlgorithmParameterException: the trustAnchors parameter must b
at java.base/sun.security.ssl.Alert.createSSLException(Alert. java: 133)
at java.base/sun.security.ss1.TransportContext. fatal (TransportContext. java: 353) at java.base/sun.security.ssl.TransportContext.fatal (TransportContext. java: 296) at java.base/sun.security.ssl.TransportContext.fatal (TransportContext. java: 291)
at java.base/sun.security.ss1.SSLSocketImp1.handleException(SSLSocketImpl.java:1690)
at java.base/sun.security.ss1.SSLSocketImp1.startHandshakeSSLSocketImpl.java:471)
at java.base/sun.security.ss1.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)

Log4j Output:

Caused by: HTTP Error -1; url='https: //login.microsoftonline.com/7389d8c0-3607-465c-a69f-7d4426502912/oauth2/token' AZUreADAuthenticator.getTokenCall threw javax.net.ssl.SSLException

Can someone help or guide here?

**Comment by venkatsunil5** [comment]
@hallihan @matthiaspfenninger - Can you please help?

**Comment by hallihan** [comment]
Please reach out to the contact listed in the README if you still need assistance. https://github.com/mspnp/spark-monitoring/tree/l4jv2#monitoring-azure-databricks-in-an-azure-log-analytics-workspace
